# Generated by Django 3.2.25 on 2024-05-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoenhance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enhancedimagemodel',
            name='enhanced_src_url',
            field=models.CharField(default='https://replicate.delivery/pbxt/qk9O3yglXV5rMpHCvdTCWfsE5UXXfJ4xF3YrXUU2Hfc284xlA/output.png', max_length=255),
            preserve_default=False,
        ),
    ]
