# Generated by Django 3.2.25 on 2024-07-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoenhance', '0002_enhancedimagemodel_enhanced_src_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='enhancedimagemodel',
            name='enhancement_model',
            field=models.CharField(default='Image Dehazing Outdoor', max_length=50),
            preserve_default=False,
        ),
    ]
